# Generated by Django 4.1 on 2022-09-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_delete_mid_1_1_delete_mid_1_2_delete_mid_2_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
