# Generated by Django 4.1 on 2022-09-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_results_1_1_grade_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='CGPA',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='SGPA_1_1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='SGPA_1_2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='SGPA_2_1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='SGPA_2_2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='SGPA_3_1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='SGPA_3_2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='SGPA_4_1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='SGPA_4_2',
            field=models.FloatField(null=True),
        ),
    ]
