# Generated by Django 4.1 on 2023-01-25 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_subjects_mid_4_2_mid_4_1_mid_3_2_mid_3_1_mid_2_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_name', models.CharField(max_length=200)),
                ('Project_Domain', models.CharField(max_length=200)),
                ('Mentor_name', models.CharField(max_length=100)),
                ('HTNO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
            options={
                'unique_together': {('HTNO', 'Project_Domain')},
            },
        ),
        migrations.CreateModel(
            name='Internships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(max_length=200)),
                ('Company_name', models.CharField(max_length=200)),
                ('Duration', models.CharField(max_length=200)),
                ('HTNO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
            options={
                'unique_together': {('HTNO', 'Role', 'Company_name')},
            },
        ),
        migrations.CreateModel(
            name='Extracircular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Domain', models.CharField(max_length=200)),
                ('Achievements', models.CharField(max_length=200)),
                ('HTNO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
            options={
                'unique_together': {('HTNO', 'Domain')},
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_name', models.CharField(max_length=200)),
                ('Course_duration', models.CharField(max_length=200)),
                ('platform_name', models.CharField(max_length=200)),
                ('HTNO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
            options={
                'unique_together': {('HTNO', 'Course_name')},
            },
        ),
        migrations.CreateModel(
            name='Activity_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Courses', models.IntegerField()),
                ('Projects', models.IntegerField()),
                ('Internships', models.IntegerField()),
                ('Extracircular', models.IntegerField()),
                ('HTNO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
            options={
                'unique_together': {('HTNO',)},
            },
        ),
    ]
