# Generated by Django 4.1 on 2023-01-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_projects_internships_extracircular_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Courses',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Extracircular',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Internships',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Projects',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Activity_count',
        ),
    ]
