# Generated by Django 4.1 on 2023-01-25 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_student_courses_student_extracircular_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projects',
            unique_together={('HTNO', 'Project_name')},
        ),
    ]
