# Generated by Django 4.1 on 2023-01-26 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_projects_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mid_1_2',
            old_name='DLS',
            new_name='STATUS',
        ),
        migrations.RenameField(
            model_name='mid_2_1',
            old_name='DLS',
            new_name='STATUS',
        ),
        migrations.RenameField(
            model_name='mid_2_2',
            old_name='DLS',
            new_name='STATUS',
        ),
        migrations.RenameField(
            model_name='mid_3_1',
            old_name='DLS',
            new_name='STATUS',
        ),
        migrations.RenameField(
            model_name='mid_3_2',
            old_name='DLS',
            new_name='STATUS',
        ),
        migrations.RenameField(
            model_name='mid_4_1',
            old_name='DLS',
            new_name='STATUS',
        ),
        migrations.RenameField(
            model_name='mid_4_2',
            old_name='DLS',
            new_name='STATUS',
        ),
        migrations.RemoveField(
            model_name='mid_1_1',
            name='DLS',
        ),
    ]
